%
%    Dynamic Evolving Neural-Fuzzy Inference System: DENFIS Plotting Function
%================================================================================
%=   Function Name:      denfisp.m                                              =
%=   Develpoer:          Qun Son                                                =
%=   Date:               October, 2000                                          =
%=   Description:        Plotting training or simulating results                =
%================================================================================
%
%   Syntax		denfisp(result, a);
%
%  here, result is a structure produced by training function or simulating 
%  function and a is a numeral for selecting different plotting kinds. If a is 
%  defined as one of 1-5, the evaluation results will be plotted, and the 
%  partition results will be plotted and if it is one of 6-9.

%--------------------------------------------------------------------------------
%   denfisp
%--------------------------------------------------------------------------------
  function  denfisp(res,varargin)

     prn = 1;
     if length(varargin) == 1
        prn = varargin{1};
     end
     
     MM.Title = 'DENFIS,  ECOS Toolbox';
     if prn > 5 & isfield(res,'Cent') & isfield(res,'Radius')
        if isfield(res, 'XData')
           if res.XData < 1;             res.XData = 1;             end;
           if res.XData > res.Ine;       res.XData = res.Ine;       end;
        else
           res.XData = 1;    
        end
        if isfield(res, 'YData')
           if res.YData < 1;             res.YData = 1;             end;
           if res.YData > res.Ine;       res.YData = res.Ine;       end;
        else
           res.YData = 2;    
        end 
        max1   = max(res.Input(:,res.XData));
        min1   = min(res.Input(:,res.XData));
        max2   = max(res.Cent(:,res.XData));
        min2   = min(res.Cent(:,res.XData));
        max0   = max([max1 max2]);
        min0   = min([min1 min2]);
        xinput = res.Input(:,res.XData);
        xcen   = res.Cent(:,res.XData); 
        MM.Maxx = max0 + 0.05*(max0-min0);
        MM.Minx = min0 - 0.05*(max0-min0);
        max1   = max(res.Input(:,res.YData));
        min1   = min(res.Input(:,res.YData));
        max2   = max(res.Cent(:,res.YData));
        min2   = min(res.Cent(:,res.YData));
        max0   = max([max1 max2]);
        min0   = min([min1 min2]);
        MM.Maxy = max0 + 0.05*(max0-min0);
        MM.Miny = min0 - 0.05*(max0-min0);
        yinput = res.Input(:,res.YData);
        ycen   = res.Cent(:,res.YData);  
        
        switch prn
        case 6
             denfisf1p_1(res,MM);
        case 7
             denfisf1p_2(res,MM);
        case 8
             denfisf1p_3(res,MM,0); 
        case 9
             denfisf1p_4(res,MM,1);       
        otherwise
             denfisf1p_1(res,MM);
        end       % switch prn
        return;
     end
     
     max1 = max(res.Out);
     max2 = max(res.OriTeach);
     min1 = min(res.Out);
     min2 = min(res.OriTeach);
     min0 = min([min1 min2]);
     max0 = max([max1 max2]);
     MM.Maxt = max0 + (max0 - min0) * 0.05;
     MM.Mint = min0 - (max0 - min0) * 0.05;
     max0 = max(abs(res.Abe));
     MM.Maxe = max0 * 1.4;
     MM.Mine = -MM.Maxe; 
     max0 = max(res.Rmse);
     min0 = min(res.Rmse);
     MM.Maxr = max0 + (max0 - min0) * 0.15;
     MM.Minr = min0 - (max0 - min0) * 0.15;
     max0 = max(res.Ndei);
     min0 = min(res.Ndei);
     MM.Maxn = max0 + (max0 - min0) * 0.15;
     MM.Minn = min0 - (max0 - min0) * 0.15;
     
     switch prn
        case 1
             denfisf1p_10(res,MM);
        case 2
             denfisf1p_11(res,MM);
        case 3
             denfisf1p_12(res,MM);
        case 4
             denfisf1p_13(res,MM);
        case 5
             denfisf1p_14(res,MM);
        otherwise
             denfisf1p_10(res,MM);
      end       % switch prn
  return;
%-------------------------------------------------------------------------------- 
%     denfisp end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_1
%--------------------------------------------------------------------------------
  function denfisf1p_1(res,MM)
 
     nd = res.Nd;
     h_deff4 = figure('position',[20 35 500 550],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     axis('square');       
     set(hf4a1,'Position',[0.01 0.07 0.98 0.87],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',10,...
               'XTick',[],'YTick',[],...
               'XLim',[MM.Minx MM.Maxx],...
               'YLim',[MM.Miny MM.Maxy]); 

     sp = ['X' int2str(res.XData) '-' 'X' int2str(res.YData)];
     xl = MM.Maxx - MM.Minx;
     yl = MM.Maxy - MM.Miny;
     yt = -0.04 * yl + MM.Miny;

     line('XData',res.Input(:,res.XData),...
          'YData',res.Input(:,res.YData),...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',3,...
          'Color',[0.7 0.7 0.7],...
          'EraseMode','none',...
          'Parent',hf4a1)
     line('XData',res.Cent(:,res.XData),...
          'YData',res.Cent(:,res.YData),...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1);

      title(['Fuzzy Rule Nodes (Cluster Centres) in ' sp ' Space']);
      xts = 0.35 * xl + MM.Minx;
      xtc = 0.60 * xl + MM.Minx;
      xss = 0.32 * xl + MM.Minx;
      xsc = 0.57 * xl + MM.Minx;
      
      text(xts, yt, 'Sample');            
      text(xtc, yt, 'Rule Node (Cluster Centre)');
      line('XData',xss,'YData',yt,...
           'LineStyle','none','LineWidth',1,...
           'Marker','o','MarkerSize',3,...
           'Color',[0 0 0],...
           'EraseMode','none',...
           'Parent',hf4a1,'Clipping','off');
      line('XData',xsc,'YData',yt,...
           'LineStyle','none','LineWidth',2,...
           'Marker','+','MarkerSize',5,...
           'Color','m',...
           'EraseMode','background',...
           'Parent',hf4a1,'Clipping','off');

  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_1 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_2
%--------------------------------------------------------------------------------
  function denfisf1p_2(res,MM)
 
     nd = res.Nd;
     h_deff4 = figure('position',[20 35 500 550],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     axis('square');       
     set(hf4a1,'Position',[0.01 0.07 0.98 0.87],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',10,...
               'XTick',[],'YTick',[],...
               'XLim',[MM.Minx MM.Maxx],...
               'YLim',[MM.Miny MM.Maxy]); 

     sp = ['X' int2str(res.XData) '-' 'X' int2str(res.YData)];
     xl = MM.Maxx - MM.Minx;
     yl = MM.Maxy - MM.Miny;
     yt = -0.04 * yl + MM.Miny;

     line('XData',res.Input(:,res.XData),...
          'YData',res.Input(:,res.YData),...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',4,...
          'Color',[0.7 0.7 0.7],...
          'EraseMode','none',...
          'Parent',hf4a1)
     line('XData',res.Cent(:,res.XData),...
          'YData',res.Cent(:,res.YData),...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1);

     title(['Partitioned Regions in ' sp ' Space']);
     xts = 0.16 * xl + MM.Minx;
     xtc = 0.37 * xl + MM.Minx;
     xss = 0.13 * xl + MM.Minx;
     xsc = 0.34 * xl + MM.Minx;

     for j = 1:res.rn
             r = res.Dthr * sqrt(2);
             x0 = res.Cent(j,res.XData);
             y0 = res.Cent(j,res.YData);
             x = [x0-r x0+r x0+r x0-r x0-r];
             y = [y0+r y0+r y0-r y0-r y0+r];
             line('XData',x,'YData',y,...
                  'LineStyle',':','LineWidth',1,...
                  'Color',[0 0 1],...
                  'EraseMode','background',...
                  'Parent',hf4a1);
     end      % j = 1:rn

     x0 = 0.775 * xl + MM.Minx;    ;
     y0 = yt;
     r  = 0.015;
     x = [x0-r x0+r x0+r x0-r x0-r];
     y = [y0+r y0+r y0-r y0-r y0+r];     
     line('XData',x,'YData',y,...
          'LineStyle',':','LineWidth',1,...
          'Color',[0 0 1],...
          'EraseMode','background',...
          'Parent',hf4a1,'Clipping','off');
     text(0.81*xl+MM.Minx, yt, 'Region');         
     text(xts, yt, 'Sample');            
     text(xtc, yt, 'Rule Node (Cluster Centre)');
     line('XData',xss,'YData',yt,...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',4,...
          'Color',[0 0 0],...
          'EraseMode','none',...
          'Parent',hf4a1,'Clipping','off');
     line('XData',xsc,'YData',yt,...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1,'Clipping','off');
 
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_2 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_3
%--------------------------------------------------------------------------------
  function denfisf1p_3(res,MM,region)
 
     h_deff4 = figure('position',[15 45 760 490],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     axis('square');       
     set(hf4a1,'Position',[0.01 0.09 0.55 0.84],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',10,...
               'XTick',[],'YTick',[],...
               'XLim',[MM.Minx MM.Maxx],...
               'YLim',[MM.Miny MM.Maxy]); 

     sp = ['X' int2str(res.XData) '-' 'X' int2str(res.YData)];
     xl = MM.Maxx - MM.Minx;
     yl = MM.Maxy - MM.Miny;
     yt = -0.04 * yl + MM.Miny;
     title(['Partition Results  in ' sp ' Space']);
     
     line('XData',res.Input(:,res.XData),...
          'YData',res.Input(:,res.YData),...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',4,...
          'Color',[0.7 0.7 0.7],...
          'EraseMode','none',...
          'Parent',hf4a1);
     line('XData',res.Cent(:,res.XData),...
          'YData',res.Cent(:,res.YData),...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1);
 
     yp = MM.Miny - 0.05 * yl;
     xts = 0.35 * xl + MM.Minx;
     xtc = 0.60 * xl + MM.Minx;
     xss = 0.32 * xl + MM.Minx;
     xsc = 0.57 * xl + MM.Minx;
      
     text(xts, yp, 'Sample');            
     text(xtc, yp, 'Rule Node (Cluster Centre)');
     line('XData',xss,'YData',yp,...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',3,...
          'Color',[0 0 0],...
          'EraseMode','none',...
          'Parent',hf4a1,'Clipping','off');
     line('XData',xsc,'YData',yp,...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1,'Clipping','off');

     hf4a12 = axes('Position',[0.64 0.73 0.34 0.20],...
                   'NextPlot','add',...
                   'Box','on',...
                   'DrawMode','fast',...
                   'FontSize',9,...
                   'XLim',[0 res.Nd],...
                   'YLim',[0 1.1*res.rn]); 
     xlabel('Samples');
     ylabel('Rules');
     line('XData',res.Crn ,'YData',1:res.rn,...
          'LineStyle','none','LineWidth',1,...
          'Marker','+','MarkerSize',3,...
          'Color',[1 0 1],...
          'EraseMode','Background',...
          'Parent',hf4a12);

     if res.EcmEpochs > 0
        maxo = max(res.Cobj);
        min0 = min(res.Cobj);
        mino = min0 - (maxo - min0) * 0.1; 
        set(hf4a12,'Position',[0.63 0.725 0.30 0.18],'Box','off');
        hf4a13 = axes('Position',[0.63 0.725 0.30 0.18],...
                      'XAxisLocation','top',...
                      'YAxisLocation','right',...
                      'Color', 'none',...
                      'NextPlot', 'add',...
                      'Box', 'off',...
                      'drawMode', 'fast',...
                      'FontSize',9,...
                      'XLim',[0 res.EcmEpochs],...
                      'YLim',[mino maxo],... 
                      'XTick',[0:1:res.EcmEpochs]); 
         xlabel('OptEpochs');
         ylabel('Obj Value');

         line('XData',0:res.EcmEpochs,'YData',res.Cobj,...
              'LineStyle','--','LineWidth',1,...
              'Color',[0.0 0.5 0.0],...
              'EraseMode','Background',...
              'Parent',hf4a13);
          
         text(MM.Minx+1.31*xl,MM.Miny+0.51*yl,...
              'Data Information','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.45*yl,...
              ['Samples   ' sprintf('%5d',res.Nd)],'Parent',hf4a1);
         text(MM.Minx+1.39*xl,MM.Miny+0.45*yl,...
              ['Inputs   ' sprintf('%5d',res.Ine)],'Parent',hf4a1);
         text(MM.Minx+1.61*xl,MM.Miny+0.45*yl,...
              ['Output  ' int2str(res.Oute)],'Parent',hf4a1);
         text(MM.Minx+1.33*xl,MM.Miny+0.37*yl,...
              'Parameters','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.31*yl,...
              'Off-line Training','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.26*yl,...
              ['Threshold     ' sprintf('%0.3f',res.Dthr)],...
               'Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.21*yl,...
              ['ECMEpochs       ' sprintf('%5d',res.EcmEpochs)],...
               'Parent',hf4a1);
         text(MM.Minx+1.52*xl,MM.Miny+0.26*yl,...
              ['M-of-N     ' sprintf('%7d',res.Mofn)],'Parent',hf4a1);
         if res.FuzzyType > 1
            text(MM.Minx+1.52*xl,MM.Miny+0.31*yl,...
                 'High-order TSK','Parent',hf4a1);
            text(MM.Minx+1.52*xl,MM.Miny+0.21*yl,...
                 ['MLPEpochs  ' sprintf('%4d',res.MLPEpochs)],...
                  'Parent',hf4a1);
         else
            text(MM.Minx+1.52*xl,MM.Miny+0.31*yl,...
                 'First-order TSK','Parent',hf4a1);           
         end
         text(MM.Minx+1.30*xl,MM.Miny+0.13*yl,...
              'Training Results','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.07*yl,...
              ['Fuzzy Rule       ' int2str(res.rn)],...
               'Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.02*yl,...
              ['ObjValue      ' sprintf('%0.3f',res.Obj)],...
               'Parent',hf4a1);
         text(MM.Minx+1.45*xl,MM.Miny+0.07*yl,...
              ['MaxDistance   ' sprintf('%0.3f',res.MaxD)],...
               'Parent',hf4a1);
         text(MM.Minx+1.45*xl,MM.Miny+0.02*yl,...
              ['CpuTime      '...
               sprintf('%0.1f',res.Time0) ' (s)'],...
               'Parent',hf4a1);
           
         yp = MM.Miny + 0.64 * yl;
         text(MM.Minx + 1.4 * xl, yp,'Cluster Number','Parent',hf4a1);
         line('XData',MM.Minx+1.3*xl,...
              'YData',yp,...
              'LineStyle','none','LineWidth',1,...
              'Marker','+','MarkerSize',3,...
              'Color',[1 0 1],...
              'EraseMode','background',...
              'Parent',hf4a1,'Clipping','off');

         yp = MM.Miny + 0.595 * yl;
         text(MM.Minx + 1.4 * xl, yp,'Objective Value','Parent',hf4a1);
         line('XData',[MM.Minx+1.25*xl MM.Minx+1.35*xl],...
              'YData',[yp yp],...
              'LineStyle','--','LineWidth',1,...
              'Color',[0 0.5 0],...
              'EraseMode','background',...
              'Parent',hf4a1,'Clipping','off');  
        return;  
     end      % if epochs > 0
       
     set(h_deff4,'CurrentAxes',hf4a1);
    
     text(MM.Minx+1.15*xl,MM.Miny+0.59*yl,'Samples');
     text(MM.Minx+1.50*xl,MM.Miny+0.59*yl,int2str(res.Nd));
     text(MM.Minx+1.15*xl,MM.Miny+0.545*yl,'Inputs');
     text(MM.Minx+1.50*xl,MM.Miny+0.545*yl,int2str(res.Ine));
     text(MM.Minx+1.15*xl,MM.Miny+0.50*yl,'Output(s)');
     text(MM.Minx+1.50*xl,MM.Miny+0.50*yl,int2str(res.Oute));
     text(MM.Minx+1.33*xl,MM.Miny+0.42*yl,'Parameters');
     text(MM.Minx+1.15*xl,MM.Miny+0.375*yl,'Training Model');
     if res.TrainMode > 1
        text(MM.Minx+1.50*xl,MM.Miny+0.375*yl,'Off-line');
     else
        text(MM.Minx+1.50*xl,MM.Miny+0.375*yl,'On-line');
     end
     text(MM.Minx+1.15*xl,MM.Miny+0.33*yl,'Fuzzy Rule Type');
     if res.FuzzyType > 1
        text(MM.Minx+1.50*xl,MM.Miny+0.33*yl,'High-order TSK'); 
     else
        text(MM.Minx+1.50*xl,MM.Miny+0.33*yl,'Firsr-order TSK'); 
     end    
     text(MM.Minx+1.15*xl,MM.Miny+0.285*yl,'Threshold');
     text(MM.Minx+1.50*xl,MM.Miny+0.285*yl,num2str(res.Dthr));
     text(MM.Minx+1.15*xl,MM.Miny+0.24*yl,'M-of-N');
     text(MM.Minx+1.50*xl,MM.Miny+0.24*yl,num2str(res.Mofn));
     text(MM.Minx+1.31*xl,MM.Miny+0.64*yl,'Data Information');   
     text(MM.Minx+1.30*xl,MM.Miny+0.16*yl,'Training Results');
     text(MM.Minx+1.15*xl,MM.Miny+0.105*yl,'Fuzzy Rules');
     text(MM.Minx+1.50*xl,MM.Miny+0.105*yl,int2str(res.rn));
     text(MM.Minx+1.15*xl,MM.Miny+0.06*yl,'ObjValue');
     text(MM.Minx+1.50*xl,MM.Miny+0.06*yl,sprintf('%0.3f',res.Obj));
     text(MM.Minx+1.15*xl,MM.Miny+0.015*yl,'MaxDistance');
     text(MM.Minx+1.50*xl,MM.Miny+0.015*yl,sprintf('%0.3f',res.MaxD));
     text(MM.Minx+1.15*xl,MM.Miny-0.03*yl,'CPU-time');
     text(MM.Minx+1.50*xl,MM.Miny-0.03*yl,...
          [sprintf('%0.3f',res.Time0) ' (s)']);
  
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_3 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_4
%--------------------------------------------------------------------------------
  function denfisf1p_4(res,MM,region)
 
     h_deff4 = figure('position',[15 45 760 490],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     axis('square');       
     set(hf4a1,'Position',[0.01 0.09 0.55 0.84],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',10,...
               'XTick',[],'YTick',[],...
               'XLim',[MM.Minx MM.Maxx],...
               'YLim',[MM.Miny MM.Maxy]); 

     sp = ['X' int2str(res.XData) '-' 'X' int2str(res.YData)];
     xl = MM.Maxx - MM.Minx;
     yl = MM.Maxy - MM.Miny;
     yt = -0.04 * yl + MM.Miny;
     title(['Partition Results  in ' sp ' Space']);
     
     line('XData',res.Input(:,res.XData),...
          'YData',res.Input(:,res.YData),...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',4,...
          'Color',[0.7 0.7 0.7],...
          'EraseMode','none',...
          'Parent',hf4a1);
     line('XData',res.Cent(:,res.XData),...
          'YData',res.Cent(:,res.YData),...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1);
 
     for j = 1:res.rn
             r  = res.Dthr * sqrt(2);
             x0 = res.Cent(j,res.XData);
             y0 = res.Cent(j,res.YData);
             x  = [x0-r x0+r x0+r x0-r x0-r];
             y  = [y0+r y0+r y0-r y0-r y0+r];            
             line('XData',x,'YData',y,...
                  'LineStyle',':','LineWidth',1,...
                  'Color',[0 0 1],...
                  'EraseMode','background',...
                  'Parent',hf4a1);
     end      % j = 1:rn
 
     yp = MM.Miny - 0.05 * yl;
     text(MM.Minx + 0.15 * xl, yp,'Sample');
     text(MM.Minx + 0.40 * xl, yp,'Region Centre');
     text(MM.Minx + 0.78 * xl, yp,'Region');
     
     line('XData',MM.Minx+0.12*xl,'YData',yp,...
          'LineStyle','none','LineWidth',1,...
          'Marker','o','MarkerSize',4,...
          'Color',[0 0 0],...
          'EraseMode','none',...
          'Parent',hf4a1,'Clipping','off');
     line('XData',MM.Minx+0.37*xl,'YData',yp,...
          'LineStyle','none','LineWidth',2,...
          'Marker','+','MarkerSize',5,...
          'Color','m',...
          'EraseMode','background',...
          'Parent',hf4a1,'Clipping','off');

     xp  = MM.Minx + 0.73 * xl;
     rx  = 0.02;
     ry  = 0.02;
     x = [xp-rx xp+rx xp+rx xp-rx xp-rx];
     y = [yp+ry yp+ry yp-ry yp-ry yp+ry];
     line('XData',x,'YData',y,...
          'LineStyle',':','LineWidth',1,...
          'Color',[0 0 1],...
          'EraseMode','background',...
          'Parent',hf4a1,'Clipping','off');
              
     hf4a12 = axes('Position',[0.64 0.73 0.34 0.20],...
                   'NextPlot','add',...
                   'Box','on',...
                   'DrawMode','fast',...
                   'FontSize',9,...
                   'XLim',[0 res.Nd],...
                   'YLim',[0 1.1*res.rn]); 
     xlabel('Samples');
     ylabel('Rules');
     line('XData',res.Crn ,'YData',1:res.rn,...
          'LineStyle','none','LineWidth',1,...
          'Marker','+','MarkerSize',3,...
          'Color',[1 0 1],...
          'EraseMode','Background',...
          'Parent',hf4a12);

     if res.EcmEpochs > 0
        maxo = max(res.Cobj);
        min0 = min(res.Cobj);
        mino = min0 - (maxo - min0) * 0.1; 
        set(hf4a12,'Position',[0.63 0.725 0.30 0.18],'Box','off');
        hf4a13 = axes('Position',[0.63 0.725 0.30 0.18],...
                      'XAxisLocation','top',...
                      'YAxisLocation','right',...
                      'Color', 'none',...
                      'NextPlot', 'add',...
                      'Box', 'off',...
                      'drawMode', 'fast',...
                      'FontSize',9,...
                      'XLim',[0 res.EcmEpochs],...
                      'YLim',[mino maxo],... 
                      'XTick',[0:1:res.EcmEpochs]); 
         xlabel('OptEpochs');
         ylabel('Obj Value');

         line('XData',0:res.EcmEpochs,'YData',res.Cobj,...
              'LineStyle','--','LineWidth',1,...
              'Color',[0.0 0.5 0.0],...
              'EraseMode','Background',...
              'Parent',hf4a13);
          
         text(MM.Minx+1.31*xl,MM.Miny+0.51*yl,...
              'Data Information','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.45*yl,...
              ['Samples   ' sprintf('%5d',res.Nd)],'Parent',hf4a1);
         text(MM.Minx+1.39*xl,MM.Miny+0.45*yl,...
              ['Inputs   ' sprintf('%5d',res.Ine)],'Parent',hf4a1);
         text(MM.Minx+1.61*xl,MM.Miny+0.45*yl,...
              ['Output  ' int2str(res.Oute)],'Parent',hf4a1);
         text(MM.Minx+1.33*xl,MM.Miny+0.37*yl,...
              'Parameters','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.31*yl,...
              'Off-line Training','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.26*yl,...
              ['Threshold     ' sprintf('%0.3f',res.Dthr)],...
               'Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.21*yl,...
              ['ECMEpochs       ' sprintf('%5d',res.EcmEpochs)],...
               'Parent',hf4a1);
         text(MM.Minx+1.52*xl,MM.Miny+0.26*yl,...
              ['M-of-N     ' sprintf('%7d',res.Mofn)],'Parent',hf4a1);
         if res.FuzzyType > 1
            text(MM.Minx+1.52*xl,MM.Miny+0.31*yl,...
                 'High-order TSK','Parent',hf4a1);
            text(MM.Minx+1.52*xl,MM.Miny+0.21*yl,...
                 ['MLPEpochs  ' sprintf('%4d',res.MLPEpochs)],...
                  'Parent',hf4a1);
         else
            text(MM.Minx+1.52*xl,MM.Miny+0.31*yl,...
                 'First-order TSK','Parent',hf4a1);           
         end
         text(MM.Minx+1.30*xl,MM.Miny+0.13*yl,...
              'Training Results','Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.07*yl,...
              ['Fuzzy Rule       ' int2str(res.rn)],...
               'Parent',hf4a1);
         text(MM.Minx+1.1*xl,MM.Miny+0.02*yl,...
              ['ObjValue      ' sprintf('%0.3f',res.Obj)],...
               'Parent',hf4a1);
         text(MM.Minx+1.45*xl,MM.Miny+0.07*yl,...
              ['MaxDistance   ' sprintf('%0.3f',res.MaxD)],...
               'Parent',hf4a1);
         text(MM.Minx+1.45*xl,MM.Miny+0.02*yl,...
              ['CpuTime      '...
               sprintf('%0.1f',res.Time0) ' (s)'],...
               'Parent',hf4a1);
           
         yp = MM.Miny + 0.64 * yl;
         text(MM.Minx + 1.4 * xl, yp,'Cluster Number','Parent',hf4a1);
         line('XData',MM.Minx+1.3*xl,...
              'YData',yp,...
              'LineStyle','none','LineWidth',1,...
              'Marker','+','MarkerSize',3,...
              'Color',[1 0 1],...
              'EraseMode','background',...
              'Parent',hf4a1,'Clipping','off');

         yp = MM.Miny + 0.595 * yl;
         text(MM.Minx + 1.4 * xl, yp,'Objective Value','Parent',hf4a1);
         line('XData',[MM.Minx+1.25*xl MM.Minx+1.35*xl],...
              'YData',[yp yp],...
              'LineStyle','--','LineWidth',1,...
              'Color',[0 0.5 0],...
              'EraseMode','background',...
              'Parent',hf4a1,'Clipping','off');  
        return;  
     end      % if epochs > 0
       
     set(h_deff4,'CurrentAxes',hf4a1);
    
     text(MM.Minx+1.15*xl,MM.Miny+0.59*yl,'Samples');
     text(MM.Minx+1.50*xl,MM.Miny+0.59*yl,int2str(res.Nd));
     text(MM.Minx+1.15*xl,MM.Miny+0.545*yl,'Inputs');
     text(MM.Minx+1.50*xl,MM.Miny+0.545*yl,int2str(res.Ine));
     text(MM.Minx+1.15*xl,MM.Miny+0.50*yl,'Output(s)');
     text(MM.Minx+1.50*xl,MM.Miny+0.50*yl,int2str(res.Oute));
     text(MM.Minx+1.33*xl,MM.Miny+0.42*yl,'Parameters');
     text(MM.Minx+1.15*xl,MM.Miny+0.375*yl,'Training Model');
     if res.TrainMode > 1
        text(MM.Minx+1.50*xl,MM.Miny+0.375*yl,'Off-line');
     else
        text(MM.Minx+1.50*xl,MM.Miny+0.375*yl,'On-line');
     end
     text(MM.Minx+1.15*xl,MM.Miny+0.33*yl,'Fuzzy Rule Type');
     if res.FuzzyType > 1
        text(MM.Minx+1.50*xl,MM.Miny+0.33*yl,'High-order TSK'); 
     else
        text(MM.Minx+1.50*xl,MM.Miny+0.33*yl,'Firsr-order TSK'); 
     end    
     text(MM.Minx+1.15*xl,MM.Miny+0.285*yl,'Threshold');
     text(MM.Minx+1.50*xl,MM.Miny+0.285*yl,num2str(res.Dthr));
     text(MM.Minx+1.15*xl,MM.Miny+0.24*yl,'M-of-N');
     text(MM.Minx+1.50*xl,MM.Miny+0.24*yl,num2str(res.Mofn));
     text(MM.Minx+1.31*xl,MM.Miny+0.64*yl,'Data Information');   
     text(MM.Minx+1.30*xl,MM.Miny+0.16*yl,'Training Results');
     text(MM.Minx+1.15*xl,MM.Miny+0.105*yl,'Fuzzy Rules');
     text(MM.Minx+1.50*xl,MM.Miny+0.105*yl,int2str(res.rn));
     text(MM.Minx+1.15*xl,MM.Miny+0.06*yl,'ObjValue');
     text(MM.Minx+1.50*xl,MM.Miny+0.06*yl,sprintf('%0.3f',res.Obj));
     text(MM.Minx+1.15*xl,MM.Miny+0.015*yl,'MaxDistance');
     text(MM.Minx+1.50*xl,MM.Miny+0.015*yl,sprintf('%0.3f',res.MaxD));
     text(MM.Minx+1.15*xl,MM.Miny-0.03*yl,'CPU-time');
     text(MM.Minx+1.50*xl,MM.Miny-0.03*yl,...
          [sprintf('%0.3f',res.Time0) ' (s)']);
  
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_4 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_10
%--------------------------------------------------------------------------------
  function denfisf1p_10(res,MM)
   
      h_deff4 = figure('position',[50 40 520 360],...
                       'numbertitle', 'off',...
                       'BackingStore','off',...
                       'resize','on',...
                       'MenuBar','figure',...
                       'Name',MM.Title);
      hf4a1 = gca;
      set(hf4a1,'Position',[0.11 0.12 0.87 0.8],...
                'NextPlot','add',...
                'Box','on',...
                'DrawMode','fast',...
                'FontSize',9,...
                'XLim',[1 res.Nd],'YLim',[MM.Mint MM.Maxt]); 
      ylabel('Actual & Desired','FontSize',10);
      title('DENFIS Evaluation','FontSize',10);

      ty = -0.1 * (MM.Maxt - MM.Mint) + MM.Mint;
      text(0.25*res.Nd, ty,' Samples','FontSize',10); 
      text(0.55*res.Nd, ty,' Actual','FontSize',10); 
      text(0.85*res.Nd, ty,' Desired','FontSize',10); 

      line('Xdata',[1:res.Nd],'Ydata',res.OriTeach,...
           'LineStyle',':','LineWidth',1,'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1);
      line('Xdata',[1:res.Nd],'Ydata',res.Out,...
           'LineStyle','none','LineWidth',1,...
           'Marker','o','MarkerSize',3,'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1);
      line('Xdata',0.53*res.Nd,'Ydata',ty,...
           'LineStyle','none','LineWidth',1,...
           'Marker','o','MarkerSize',3,'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');
      line('Xdata',[0.73*res.Nd 0.83*res.Nd],'Ydata',[ty ty],...
           'LineStyle',':','LineWidth',1,'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');
  
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_10 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_11
%--------------------------------------------------------------------------------
  function denfisf1p_11(res,MM)
  
     h_deff4 = figure('position',[50 40 520 360],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
      hf4a1 = gca;
      set(hf4a1,'Position',[0.11 0.12 0.87 0.8],...
                'NextPlot','add',...
                'Box','on',...
                'DrawMode','fast',...
                'FontSize',9,...
                'XLim',[1 res.Nd],'YLim',[MM.Mint MM.Maxt]); 
      ylabel('Actual & Desired','FontSize',10);
      title('DENFIS Evaluation','FontSize',10);

      ty = -0.1 * (MM.Maxt - MM.Mint) + MM.Mint;
      text(0.25*res.Nd, ty,' Samples','FontSize',10); 
      text(0.60*res.Nd, ty,' Actual','FontSize',10); 
      text(0.85*res.Nd, ty,' Desired','FontSize',10); 

      line('Xdata',[1:res.Nd],'Ydata',res.Out,...
           'LineStyle','-','LineWidth',1,'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1);

      line('Xdata',[1:res.Nd],'Ydata',res.OriTeach,...
           'LineStyle','--','LineWidth',1,'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1);

      line('Xdata',[0.48*res.Nd 0.58*res.Nd],'Ydata',[ty ty],...
           'LineStyle','-','LineWidth',1,'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');

      line('Xdata',[0.73*res.Nd 0.83*res.Nd],'Ydata',[ty ty],...
           'LineStyle','--','LineWidth',1,'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');
 
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_11 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_12
%--------------------------------------------------------------------------------
  function denfisf1p_12(res,MM)
 
     nd = res.Nd;
     h_deff4 = figure('position',[50 40 520 510],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     set(hf4a1,'Position',[0.11 0.37 0.87 0.57],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',9,...
               'XLim',[1 nd],'YLim',[MM.Mint MM.Maxt]); 
     ylabel('Actual & Desired','FontSize',10);
     title('DENFIS Evaluation','FontSize',10);
     
     ty = -0.1 * (MM.Maxt - MM.Mint) + MM.Mint;
     text(0.25*nd, ty,' Samples','FontSize',10); 
     text(0.60*nd, ty,' Actual','FontSize',10); 
     text(0.85*nd, ty,' Desired','FontSize',10); 
        
     hf4a2 = axes('Position',[0.11 0.08 0.87 0.19],...
                  'NextPlot','add',...
                  'Box','on',...
                  'DrawMode','fast',...
                  'FontSize',9,...
                  'XLim',[1 nd],'YLim',[MM.Mine MM.Maxe]); 
     xlabel('Samples','FontSize',10);
     ylabel('Error','FontSize',10);

     line('Xdata',[1:nd],'Ydata',res.Out,...
          'LineStyle','-',...
          'LineWidth',1,...
          'Color',[0 0 0],...
          'EraseMode','none','Parent',hf4a1);
     line('Xdata',[1:nd],'Ydata',res.OriTeach,...
          'LineStyle','--',...
          'LineWidth',1,...
          'Color',[1 0 0],...
          'EraseMode','none','Parent',hf4a1);       
     line('Xdata',[0.48*nd 0.58*nd],'Ydata',[ty ty],...
          'LineStyle','-','LineWidth',1,'Color',[0 0 0],...
          'EraseMode','none','Parent',hf4a1,'Clipping','off');
     line('Xdata',[0.73*nd 0.83*nd],'Ydata',[ty ty],...
          'LineStyle','--','LineWidth',1,'Color',[1 0 0],...
          'EraseMode','none','Parent',hf4a1,'Clipping','off');
     line('Xdata',[1 nd],'Ydata',[0 0],...
          'LineStyle',':',...
          'LineWidth',1,...
          'Color',[0 1 0],...
          'EraseMode','none','Parent',hf4a2);
     line('Xdata',[1:nd],'Ydata',res.Abe,...
          'LineStyle','-',...
          'LineWidth',1,...
          'Color',[0 0 1],...
          'EraseMode','none','Parent',hf4a2);
 
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_12 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_13
%--------------------------------------------------------------------------------
  function denfisf1p_13(res,MM)
 
     nd = res.Nd;
     h_deff4 = figure('position',[50 38 520 600],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
      hf4a1 = gca;
      set(hf4a1,'Position',[0.11 0.54 0.87 0.41],...
                'NextPlot','add',...
                'Box','on',...
                'DrawMode','fast',...
                'FontSize',9,...
                'XLim',[1 nd],'YLim',[MM.Mint MM.Maxt]); 
      ylabel('Actual & Desired','FontSize',10);
      title('DENFIS Evaluation','FontSize',10);

      ty = -0.12 * (MM.Maxt - MM.Mint) + MM.Mint;
      text(0.25*nd, ty,' Samples','FontSize',10); 
      text(0.60*nd, ty,' Actual','FontSize',10); 
      text(0.85*nd, ty,' Desired','FontSize',10); 
        
      hf4a2 = axes('Position',[0.11 0.28 0.87 0.17],...
                   'NextPlot','add',...
                   'Box','on',...
                   'DrawMode','fast',...
                   'FontSize',9,...
                   'XLim',[1 nd],'YLim',[MM.Mine MM.Maxe]); 
      xlabel('Samples','FontSize',10);
      ylabel('Error','FontSize',10);
        
      hf4a3 = axes('Position',[0.11 0.06 0.37 0.145],...
                   'NextPlot','add',...
                   'Box','on',...
                   'DrawMode','fast',...
                   'FontSize',9,...
                   'XLim',[1 nd],'YLim',[MM.Minr MM.Maxr]); 
      xlabel('Samples','FontSize',10);
      ylabel('RMSE','FontSize',10);
        
      hf4a4 = axes('Position',[0.61 0.06 0.37 0.145],...
                   'NextPlot','add',...
                   'Box','on',...
                   'DrawMode','fast',...
                   'FontSize',9,...
                   'XLim',[1 nd],'YLim',[MM.Minn MM.Maxn]); 
      xlabel('Samples','FontSize',10);
      ylabel('NDEI','FontSize',10);

      line('Xdata',[1:nd],'Ydata',res.Out,...
           'LineStyle','-',...
           'LineWidth',1,...
           'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1);
      line('Xdata',[1:nd],'Ydata',res.OriTeach,...
           'LineStyle','--',...
           'LineWidth',1,...
           'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1);
      line('Xdata',[0.48*nd 0.58*nd],'Ydata',[ty ty],...
           'LineStyle','-','LineWidth',1,'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');
      line('Xdata',[0.73*nd 0.83*nd],'Ydata',[ty ty],...
           'LineStyle','--','LineWidth',1,'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a1,'Clipping','off');  
      line('Xdata',[1 nd],'Ydata',[0 0],...
           'LineStyle',':',...
           'LineWidth',1,...
           'Color',[0 1 0],...
           'EraseMode','none','Parent',hf4a2);
      line('Xdata',[1:nd],'Ydata',res.Abe,...
           'LineStyle','-',...
           'LineWidth',1,...
           'Color',[0 0 1],...
           'EraseMode','none','Parent',hf4a2);
      line('Xdata',[1:nd],'Ydata',res.Rmse,...
           'LineStyle','-',...
           'LineWidth',1,...
           'Color',[0 0 0],...
           'EraseMode','none','Parent',hf4a3);
      line('Xdata',[1:nd],'Ydata',res.Ndei,...
           'LineStyle','--',...
           'LineWidth',1,...
           'Color',[1 0 0],...
           'EraseMode','none','Parent',hf4a4);

  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_13 end
%--------------------------------------------------------------------------------

%-------------------------------------------------------------------------------- 
%     denfisf1p_14
%--------------------------------------------------------------------------------
  function denfisf1p_14(res,MM)
 
     nd = res.Nd;
     h_deff4 = figure('position',[50 38 520 655],...
                      'numbertitle', 'off',...
                      'BackingStore','off',...
                      'resize','on',...
                      'MenuBar','figure',...
                      'Name',MM.Title);
     hf4a1 = gca;
     set(hf4a1,'Position',[0.11 0.61 0.87 0.34],...
               'NextPlot','add',...
               'Box','on',...
               'DrawMode','fast',...
               'FontSize',9,...
               'XLim',[1 nd],'YLim',[MM.Mint MM.Maxt]); 
     ylabel('Actual & Desired','FontSize',10);
     title('DENFIS Evaluation','FontSize',10);

     ty = -0.12 * (MM.Maxt - MM.Mint) + MM.Mint;
     text(0.25*nd, ty,' Samples','FontSize',10); 
     text(0.60*nd, ty,' Actual','FontSize',10); 
     text(0.85*nd, ty,' Desired','FontSize',10); 
     ty0 = - (MM.Maxt - MM.Mint);
     text(0.63*nd, 0.80*ty0+MM.Mint,'Samples','FontSize',10); 
     text(0.63*nd, 0.90*ty0+MM.Mint,'Input(s)','FontSize',10);
     text(0.63*nd, 1.00*ty0+MM.Mint,'Output(s)','FontSize',10);
     text(0.63*nd, 1.10*ty0+MM.Mint,'Training','FontSize',10);
     text(0.63*nd, 1.20*ty0+MM.Mint,'Rule-Type','FontSize',10);
     text(0.63*nd, 1.30*ty0+MM.Mint,'Rules','FontSize',10); 
     text(0.63*nd, 1.40*ty0+MM.Mint,'M-of-N','FontSize',10);
     text(0.63*nd, 1.50*ty0+MM.Mint,'RMSE','FontSize',10); 
     text(0.63*nd, 1.60*ty0+MM.Mint,'NDEI','FontSize',10);
     text(0.83*nd, 0.80*ty0+MM.Mint,int2str(nd),'FontSize',10); 
     text(0.83*nd, 0.90*ty0+MM.Mint,int2str(res.Ine),'FontSize',10); 
     text(0.83*nd, 1.00*ty0+MM.Mint,int2str(res.Oute),'FontSize',10);

     if res.FuzzyType > 1
        text(0.83*nd, 1.20*ty0+MM.Mint,'High-order','FontSize',10);
        %text(0.63*nd, 1.70*ty0+MM.Mint,'S1 ','FontSize',10); 
        %text(0.83*nd, 1.70*ty0+MM.Mint,num2str(res.Tparm(9)),'FontSize',10); 
     else
        text(0.83*nd, 1.20*ty0+MM.Mint,'First-order','FontSize',10);
     end
     if res.TrainMode > 1
        text(0.83*nd, 1.10*ty0+MM.Mint,'Off-line','FontSize',10); 
     else
        text(0.83*nd, 1.10*ty0+MM.Mint,'On-line','FontSize',10); 
     end
     text(0.83*nd, 1.30*ty0+MM.Mint,int2str(res.rn),'FontSize',10); 
     text(0.83*nd, 1.40*ty0+MM.Mint,int2str(res.Mofn),'FontSize',10);
     text(0.83*nd, 1.50*ty0+MM.Mint,...
          sprintf('%0.3f',res.Rmse(res.Nd)),'FontSize',10); 
     text(0.83*nd, 1.60*ty0+MM.Mint,...
          sprintf('%0.3f',res.Ndei(res.Nd)),'FontSize',10);
      
     hf4a2 = axes('Position',[0.11 0.42 0.87 0.115],...
                  'NextPlot','add',...
                  'Box','on',...
                  'DrawMode','fast',...
                  'FontSize',9,...
                  'XLim',[1 nd],'YLim',[MM.Mine MM.Maxe]); 
     xlabel('Samples','FontSize',10);
     ylabel('Error','FontSize',10);
        
     hf4a3 = axes('Position',[0.11 0.24 0.48 0.11],...
                  'NextPlot','add',...
                  'Box','on',...
                  'DrawMode','fast',...
                  'FontSize',9,...
                  'XLim',[1 nd],'YLim',[MM.Minr MM.Maxr]); 
     xlabel('Samples','FontSize',10);
     ylabel('RMSE','FontSize',10);
        
     hf4a4 = axes('Position',[0.11 0.06 0.48 0.11],...
                  'NextPlot','add',...
                  'Box','on',...
                  'DrawMode','fast',...
                  'FontSize',9,...
                  'XLim',[1 nd],'YLim',[MM.Minn MM.Maxn]); 
     xlabel('Samples','FontSize',10);
     ylabel('NDEI','FontSize',10);

     line('Xdata',[1:nd],'Ydata',res.Out,...
          'LineStyle','-',...
          'LineWidth',1,...
          'Color',[0 0 0],...
          'EraseMode','none','Parent',hf4a1);
     line('Xdata',[1:nd],'Ydata',res.OriTeach,...
          'LineStyle','--',...
          'LineWidth',1,...
          'Color',[1 0 0],...
          'EraseMode','none','Parent',hf4a1);
     line('Xdata',[0.48*nd 0.58*nd],'Ydata',[ty ty],...
          'LineStyle','-','LineWidth',1,'Color',[0 0 0],...
          'EraseMode','none','Parent',hf4a1,'Clipping','off');
     line('Xdata',[0.73*nd 0.83*nd],'Ydata',[ty ty],...
          'LineStyle','--','LineWidth',1,'Color',[1 0 0],...
          'EraseMode','none','Parent',hf4a1,'Clipping','off');
     line('Xdata',[1 nd],'Ydata',[0 0],...
          'LineStyle',':',...
          'LineWidth',1,...
          'Color',[0 1 0],...
          'EraseMode','none','Parent',hf4a2);
     line('Xdata',[1:nd],'Ydata',res.Abe,...
          'LineStyle','-',...
          'LineWidth',1,...
          'Color',[0 0 1],...
          'EraseMode','none','Parent',hf4a2);
     line('Xdata',[1:nd],'Ydata',res.Rmse,...
          'LineStyle','-',...
          'LineWidth',1,...
          'Color',[0 0 0],...
          'EraseMode','none','Parent',hf4a3);
     line('Xdata',[1:nd],'Ydata',res.Ndei,...
          'LineStyle','--',...
          'LineWidth',1,...
          'Color',[1 0 0],...
          'EraseMode','none','Parent',hf4a4);
  return;
%-------------------------------------------------------------------------------- 
%     denfisf1p_14 end
%--------------------------------------------------------------------------------
